### ISSUE TITLE
Player one will always win if both players make the same guess as each other

### ISSUE THREAD

**Issue by charlie2099** [charlie2099/Data-Visualisation-Game#1]
**Describe the bug**
When both players make the same guess player one will always win.

**To Reproduce**
1. Utilising the guess slider, have both players make the same guess on a cities crime data
2. Player one wins

**Expected behavior**
Both players should win a point if they make the same guess as each other and it is close to the real answer. 

**Screenshots**
![same_score_issue](https://user-images.githubusercontent.com/55750961/200035728-dd8c54b4-b4a5-4c06-80a7-c3c6b474cf4f.png)

**Desktop (please complete the following information):**
N/A

**Additional context**
None

**Comment by int-Kaan** [comment]
FIXED
